### PR TITLE
Publish v3.6.0 Add Portuguese Translation

### PR DESCRIPTION
**Pull request by huayunh**
#### Changes proposed in this Pull Request:
- Add Portuguese translation
- Fixed type checking for errors

### CODE REVIEW

**Comment by emclaug2** [comment]
@huayunh @daileytj  Is this ready to go in?

**Comment by daileytj** [comment]
@emclaug2 I'd say so, not sure why it's still a draft ¯\_(ツ)_/¯

**Comment by huayunh** [comment]
ah yes. I forgot. Meant to change it after the date change PR. Thanks Tom.

**Comment by huayunh** [comment]
Now it's outdated again 🙈

**Comment by daileytj** [comment]
@huayunh I can fix it

**Review by emclaug2 — APPROVED** [review]

**Review by daileytj — APPROVED** [review]

**Pull request merged**
