### PR TITLE
Add some alternative translation strings

### PR DESCRIPTION
**Pull request by joebochill**
#### Changes proposed in this Pull Request:
- Add some alternative strings that can be used by the Trans component from i18next-react for formatting string internals
- Add a new Auth action to reset the transit state for login request
- Update lint dependencies

### CODE REVIEW

**Comment by jeffvg** [comment]
@emclaug2 brought this up several days ago and thought it was updated. I can blow by the create account (details) page.

image

**Comment by joebochill** [comment]
@jeffvg that should be fixed in the react-workflows repository now.

**Comment by emclaug2** [comment]
Looks good to me!

**Comment by joebochill** [comment]
Jeff is logging a new issue for French not working on Android, but that issue seems to pre-date these string updates.

**Comment by jeffvg** [comment]
noticed this done button in lower right corner that slides up when selecting verification field.
Screen Shot 2020-08-28 at 9 17 30 AM

**Comment by joebochill** [comment]
I have a fix for that button that I'll push up with a couple other bug fixes on the react-native-workflows

**Pull request merged**
